---
- hosts: all
  tasks:
  - name: Install packages
    apt: pkg={{ item }} state=present update_cache=yes
    with_items:
      - python3.4
      - python3-pip
      - python3.4-venv

  - name: Install requirements.txt
    pip: requirements=/vagrant/requirements.txt executable=pip3

  - name: Update virtualenv
    pip: requirements=/vagrant/requirements.txt virtualenv_command=pyvenv-3.4 virtualenv=/vagrant/venv executable=pip3

  - name: update bash_profile to start virtualenv
    shell: echo "source /vagrant/venv/bin/activate" >> .bash_profile